spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/cars
        username: postgres
        password: 12345

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    time_zone: UTC
